message: "Hello from default v2"
profileSpecificMessage: "Profile Message from default"
valueMessage: "Message from value variable v2"

---
spring:
  config:
    activate:
      on-profile: local
profileSpecificMessage: "Profile Message from local"

---
spring:
  config:
    activate:
      on-profile: asae
profileSpecificMessage: "Profile Message from Azure Spring Apps Enterprise "
