spring:
  config:
    activate:
      on-profile: local
message: "Hello from Local !!"

---
spring:
  config:
    activate:
      on-profile: default
message: "Hello from Default v2 !!"

---
spring:
  config:
    activate:
      on-profile: asae
message: "Hello from Azure Spring Apps Enterprise !!"
